#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status aws root_indicator background_jobs history time)
DEFAULT_USER=$USER

## AWS
function agp {
  echo $AWS_DEFAULT_PROFILE
}

function asp {
  export AWS_DEFAULT_PROFILE=$1
  export AWS_PROFILE=$1
  export AWS_EB_PROFILE=$1
}
if [ $commands[aws] ]; then
  source /usr/local/share/zsh/site-functions/aws_zsh_completer.sh
fi

## GPG
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
#gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye

## Kubectl
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
  alias k='kubectl'
fi

## JX
if [ $commands[jx] ]; then
  source <(jx completion zsh)
fi
